### ISSUE TITLE
Exceeding some character count results in a memory related crash

### ISSUE THREAD

**Issue by meshantz** [ycw/Babylon.Font#22]
This seems to be both font and character specific.

Experimenting with the `NotoSansMono-Thin` and updating the example (`bare/index.js`)  text value to 241 `*` characters results in the following traceback:

```
bf.0.1.0.babylon.font.wasm:0x237 Uncaught (in promise) RuntimeError: memory access out of bounds
    at bf.0.1.0.babylon.font.wasm:0x237
    at bf.0.1.0.babylon.font.wasm:0x268
    at bf.0.1.0.babylon.font.wasm:0xed
    at bf.0.1.0.babylon.font.wasm:0x6f5
    at bf.0.1.0.babylon.font.wasm:0xb37
    at bf.0.1.0.babylon.font.wasm:0x250d
    at bf.0.1.0.babylon.font.wasm:0x207c
    at curr.<computed> [as compile] (loader.js:379:18)
    at Compiler.compileEncoded (babylon.font.js:104:45)
    at Compiler.compile (babylon.font.js:146:21)
```

Using 241 `l` characters instead, does not result in this crash. Other fonts can result in much lower limits before this happens.

Is this some kind of natural limitation (if so, is there a calculation that can prevent it) or a bug in memory management somewhere?

**Comment by ycw** [comment]
increase the budget in asconfig.json:options.memoryBase ( say, 655360 = 640kB )

https://github.com/ycw/Babylon.Font/blob/0d0c9420a569769200365eaeddb50c12fac1d8bf/asconfig.json#L18

then rebuild (npm run asbuild) 

🥂

**Comment by meshantz** [comment]
Okay, that makes sense. Thanks for the quick reply!

Is there a way to calculate what values will be a problem for a given font, or is the only way to wrap every call to `builder.create` with error handling to catch this error?

**Comment by meshantz** [comment]
Hmm. I can't seem to recover from this error at all. I've even tried reloading the entire complier mechanism (which would be pretty  heavy to do _every time_ this error occurs) to no avail. 

All subsequent calls to `builder.create` fail with the same error.

Here is (roughly) the reloading code I attempted:

```
  let compiler = await Compiler.Build(`${constants.BABYLON_FONT_WASM}`)

  let fonts: { [key in FontName]: Font } = {
    calibri: await Font.Install(fontPaths.calibri, compiler, opentype),
    consola: await Font.Install(fontPaths.consola, compiler, opentype),
    'consola-bold': await Font.Install(
      fontPaths['consola-bold'],
      compiler,
      opentype,
    ),
  }

  let builder = new TextMeshBuilder(BABYLON, earcut)

      try {
        mesh = builder.create(
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-ignore
          {
            font: fonts.calibri,
            text: failingText,
            size: 12,
          },
          scene,
        )
      } catch (error) {
        Compiler.Build(`${constants.BABYLON_FONT_WASM}`).then(
          async (newCompiler) => {
            compiler = newCompiler
            fonts = {
              calibri: await Font.Install(
                fontPaths.calibri,
                compiler,
                opentype,
              ),
              consola: await Font.Install(
                fontPaths.consola,
                compiler,
                opentype,
              ),
              'consola-bold': await Font.Install(
                fontPaths['consola-bold'],
                compiler,
                opentype,
              ),
            }
            builder = new TextMeshBuilder(BABYLON, earcut)
            builder.create(
              // eslint-disable-next-line @typescript-eslint/ban-ts-comment
              // @ts-ignore
              {
                font: fonts.calibri,
                text: 'small',
                size: 12,
              },
              makeOpts.scene,
            )
          },
        )
      }
```

**Comment by ycw** [comment]
a workaround off the top of my head

bytes required for `(font, text)` can be computed by: 

```js
function bytes_required(font, text) {
  let b = 0
  const cmds = font.raw.getPath(text, 0, 0, 100).commands
  for (const cmd of cmds) {
    b += 1
    switch (cmd.type) {
      case 'M': 
      case 'L': b += 16; break
      case 'Q': b += 48; break
      case 'C': b += 64; break 
    }
  }
  return b
}
```

then, validate before each `builder.create`: 

```js
if ( bytes_required(font, 'hello') <= 65536 ) {
  // builder.create( .. )
} 
```

where 65536 := asconfig.json:options.memoryBase  

🥂

**Comment by meshantz** [comment]
Awesome. Thanks again! I'll give this a shot.

**Comment by ycw** [comment]
solved in [v4](https://github.com/ycw/Babylon.Font/releases/tag/v4.0.0).
